---
apiVersion: v1
kind: Service
metadata:
  name: mynginx
spec:
  selector:
    app: mynginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynginx
  labels:
    app: mynginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mynginx
  template:
    metadata:
      labels:
        app: mynginx
    spec:
      nodeSelector:
        nodetype: back
      containers:
      - name: mynginx
        image: nginx:latest
        ports:
        - containerPort: 80